import { Shirt, Sparkles, UtensilsCrossed, Smartphone, Home, Package } from 'lucide-react'

// Catalogue de presets industrie pour l'onboarding 1-clic.
// Chaque preset configure : brand_tone, 15 entrees knowledge_base, 5 guardrails, 3 playbooks.
// Les noms de playbooks correspondent aux `name` existants dans engine_playbooks.
export const INDUSTRY_PRESETS = [
  {
    id: 'fashion',
    name: 'Mode & Vetements',
    icon: Shirt,
    description: 'Vetements, accessoires, chaussures',
    color: '#ec4899',
    brand_tone: 'Chaleureux, expert mode, conseil personnalise',
    knowledge: [
      { q: 'Quels sont vos delais de livraison ?', a: '2-5 jours ouvres en France metropolitaine, 5-10 jours en Europe.' },
      { q: 'Comment retourner un article ?', a: 'Vous avez 30 jours pour retourner un article non porte avec etiquette. Retour gratuit en France.' },
      { q: 'Comment choisir ma taille ?', a: 'Consultez notre guide des tailles sur chaque fiche produit. En cas de doute, prenez la taille au-dessus.' },
      { q: 'Puis-je echanger un article ?', a: 'Oui, l echange est possible sous 30 jours. Contactez-nous avec votre numero de commande.' },
      { q: 'Les articles sont-ils en stock ?', a: 'Tous les articles affiches en ligne sont en stock. La disponibilite est mise a jour en temps reel.' },
      { q: 'Comment suivre ma commande ?', a: 'Un email avec le numero de suivi vous est envoye des l expedition. Vous pouvez aussi consulter votre compte.' },
      { q: 'Quels sont les moyens de paiement ?', a: 'Carte bancaire, PayPal, Apple Pay et paiement en 3x sans frais des 100 euros d achat.' },
      { q: 'Livrez-vous a l international ?', a: 'Oui, nous livrons dans toute l Europe et au Royaume-Uni. Les frais varient selon la destination.' },
      { q: 'Comment entretenir mes vetements ?', a: 'Les conseils d entretien sont sur l etiquette de chaque article et sur la fiche produit.' },
      { q: 'Les matieres sont-elles eco-responsables ?', a: 'Nous privilegions des matieres certifiees (coton bio, lin, laine recyclee). Les details sont sur chaque fiche produit.' },
      { q: 'Ai-je droit a une reduction sur ma premiere commande ?', a: 'Oui, inscrivez-vous a la newsletter pour recevoir un code de bienvenue de 10 pourcent.' },
      { q: 'Combien coute la livraison ?', a: 'Livraison gratuite des 50 euros d achat, sinon 4,90 euros en France metropolitaine.' },
      { q: 'Puis-je modifier ma commande ?', a: 'Oui, tant qu elle n est pas expediee. Contactez-nous rapidement avec votre numero de commande.' },
      { q: 'Avez-vous un programme de fidelite ?', a: 'Oui, chaque achat vous rapporte des points echangeables contre des reductions sur vos prochaines commandes.' },
      { q: 'Comment recuperer mon avoir ?', a: 'Votre avoir est valable 12 mois et utilisable en une ou plusieurs fois sur le site avec le code fourni.' },
    ],
    guardrails: [
      'Ne JAMAIS recommander un produit qui n est pas dans le catalogue Shopify',
      'Toujours proposer un echange avant un remboursement',
      'Si le client demande un avis style/conseil, rester neutre et factuel',
      'Ne jamais promettre un delai de livraison express sans avoir verifie le stock',
      'En cas de litige sur la taille, proposer toujours un retour gratuit',
    ],
    playbooks: ['sav_ecommerce', 'abandoned_cart', 'shipping_tracker'],
  },
  {
    id: 'cosmetics',
    name: 'Cosmetiques & Beaute',
    icon: Sparkles,
    description: 'Maquillage, soins, parfums',
    color: '#f59e0b',
    brand_tone: 'Elegant, expert beaute, bienveillant',
    knowledge: [
      { q: 'Vos produits sont-ils testes sur les animaux ?', a: 'Non, aucun de nos produits ni leurs ingredients ne sont testes sur les animaux. Nous sommes certifies cruelty-free.' },
      { q: 'Vos produits sont-ils vegan ?', a: 'La majorite de notre gamme est vegan. Verifiez la mention "Vegan" sur la fiche produit.' },
      { q: 'Puis-je retourner un produit ouvert ?', a: 'Pour des raisons d hygiene, les produits ouverts ne peuvent pas etre retournes sauf defaut.' },
      { q: 'Quels sont les ingredients ?', a: 'La liste complete des ingredients (INCI) est disponible sur chaque fiche produit.' },
      { q: 'Comment savoir si un produit me convient ?', a: 'Indiquez-nous votre type de peau et nous vous orienterons vers le produit le plus adapte.' },
      { q: 'Quelle est la duree de vie apres ouverture ?', a: 'Le symbole PAO (pot ouvert) sur le packaging indique la duree de conservation apres ouverture.' },
      { q: 'Delais de livraison ?', a: '2-4 jours ouvres en France. Livraison offerte des 40 euros d achat.' },
      { q: 'Les produits conviennent-ils aux peaux sensibles ?', a: 'De nombreux produits sont formules pour peaux sensibles. Regardez la mention sur la fiche produit.' },
      { q: 'Offrez-vous des echantillons ?', a: 'Oui, 2 echantillons gratuits sont offerts pour toute commande superieure a 30 euros.' },
      { q: 'Comment conserver mes produits ?', a: 'A l abri de la lumiere, de l humidite et de la chaleur pour preserver leur efficacite.' },
      { q: 'Que faire en cas de reaction ?', a: 'Arretez immediatement l utilisation du produit et consultez un dermatologue si les symptomes persistent.' },
      { q: 'Avez-vous des produits bio ?', a: 'Oui, nos produits certifies bio portent le label Cosmos Organic ou Ecocert sur la fiche produit.' },
      { q: 'Puis-je recevoir un diagnostic de peau ?', a: 'Oui, remplissez notre questionnaire en ligne pour recevoir des recommandations personnalisees.' },
      { q: 'Ou sont fabriques vos produits ?', a: 'La majorite de notre gamme est fabriquee en France. L origine est indiquee sur chaque fiche produit.' },
      { q: 'Comment utiliser un code promo ?', a: 'Entrez le code dans le champ "code promo" au moment du paiement avant de valider votre commande.' },
    ],
    guardrails: [
      'Ne JAMAIS donner de conseil medical, toujours rediriger vers un dermatologue',
      'Ne jamais affirmer qu un produit traite une pathologie',
      'En cas de reaction allergique, arreter le produit et consulter un medecin',
      'Respecter les contre-indications listees sur les fiches produits',
      'Ne jamais comparer negativement a un concurrent',
    ],
    playbooks: ['sav_ecommerce', 'post_purchase_followup', 'abandoned_cart'],
  },
  {
    id: 'food',
    name: 'Alimentaire & Boissons',
    icon: UtensilsCrossed,
    description: 'Epicerie fine, boissons, gastronomie',
    color: '#10b981',
    brand_tone: 'Convivial, gourmand, passionne',
    knowledge: [
      { q: 'Quelle est la duree de conservation ?', a: 'La DLC ou DDM est indiquee sur chaque produit et au moment de la livraison.' },
      { q: 'Livraison sous chaine du froid ?', a: 'Oui, tous nos produits frais sont livres en colis isotherme avec packs de glace.' },
      { q: 'Que faire si un produit arrive abime ?', a: 'Envoyez-nous une photo dans les 24h, nous remplacons ou remboursons immediatement.' },
      { q: 'Allergenes ?', a: 'La liste des allergenes est indiquee sur chaque fiche produit conformement a la reglementation.' },
      { q: 'Bio ?', a: 'Nos produits bio sont certifies et portent le label AB ou Eurofeuille.' },
      { q: 'Delais de livraison ?', a: '24-48h en France pour les produits frais, 2-4 jours pour l epicerie seche.' },
      { q: 'Livrez-vous le week-end ?', a: 'Nous livrons du mardi au samedi. Passez commande avant 14h pour une expedition le jour meme.' },
      { q: 'Quels sont les frais de livraison ?', a: 'Livraison offerte des 60 euros d achat, sinon 8,90 euros pour le frais et 4,90 euros pour le sec.' },
      { q: 'Vos produits sont-ils locaux ?', a: 'Nous privilegions des producteurs francais et europeens. L origine est indiquee sur chaque fiche produit.' },
      { q: 'Puis-je commander pour un evenement ?', a: 'Oui, contactez-nous pour les commandes professionnelles ou evenementielles superieures a 200 euros.' },
      { q: 'Comment conserver les produits a reception ?', a: 'Placez immediatement les produits frais au refrigerateur et les surgeles au congelateur.' },
      { q: 'Proposez-vous des coffrets cadeaux ?', a: 'Oui, decouvrez notre selection de coffrets prets a offrir, avec emballage cadeau inclus.' },
      { q: 'Puis-je personnaliser ma commande ?', a: 'Oui, ajoutez une note lors de la commande et nous ferons notre possible pour repondre a votre demande.' },
      { q: 'Que faire si un produit manque ?', a: 'Contactez-nous avec une photo du colis recu. Nous renvoyons immediatement le produit manquant.' },
      { q: 'Avez-vous des offres de parrainage ?', a: 'Oui, chaque filleul vous rapporte 10 euros de credit utilisable sur votre prochaine commande.' },
    ],
    guardrails: [
      'Toujours mentionner les allergenes en cas de doute',
      'Ne JAMAIS donner de conseil nutritionnel precis',
      'Pour les produits frais, toujours rappeler la chaine du froid',
      'En cas de reclamation produit non conforme, demander une photo immediatement',
      'Ne jamais affirmer un benefice sante non prouve',
    ],
    playbooks: ['sav_ecommerce', 'shipping_tracker', 'abandoned_cart'],
  },
  {
    id: 'electronics',
    name: 'Electronique & Tech',
    icon: Smartphone,
    description: 'Smartphones, accessoires, gadgets',
    color: '#3b82f6',
    brand_tone: 'Precis, technique, pedagogue',
    knowledge: [
      { q: 'Garantie ?', a: 'Tous nos produits sont garantis 2 ans (garantie legale de conformite).' },
      { q: 'Comment obtenir le SAV ?', a: 'Contactez-nous avec votre numero de commande et une description du probleme, nous prenons en charge.' },
      { q: 'Compatibilite ?', a: 'La liste des compatibilites est sur chaque fiche produit. En cas de doute, donnez-nous votre modele.' },
      { q: 'Notice ?', a: 'La notice est livree avec chaque produit et telechargeable en PDF sur la fiche produit.' },
      { q: 'Certificat CE ?', a: 'Tous nos produits sont conformes aux normes CE et certifies.' },
      { q: 'Delais de livraison ?', a: '24-48h en France metropolitaine. Livraison gratuite des 50 euros d achat.' },
      { q: 'Puis-je retourner un produit ?', a: 'Oui, vous disposez de 30 jours pour retourner un produit non utilise dans son emballage d origine.' },
      { q: 'Le produit est-il reconditionne ou neuf ?', a: 'Sauf mention "reconditionne" sur la fiche produit, tous nos articles sont neufs sous blister.' },
      { q: 'Que faire en cas de panne ?', a: 'Contactez-nous avec une description de la panne. Nous organisons un diagnostic et une prise en charge sous garantie.' },
      { q: 'Proposez-vous une extension de garantie ?', a: 'Oui, une extension de 1 ou 2 ans supplementaires est disponible a l ajout au panier.' },
      { q: 'Facture TVA ?', a: 'Une facture HT/TTC est automatiquement generee et envoyee par email apres chaque achat.' },
      { q: 'Les accessoires sont-ils inclus ?', a: 'Tous les accessoires fournis sont listes dans l onglet "contenu de la boite" de la fiche produit.' },
      { q: 'Firmware a jour ?', a: 'Nos produits sont livres avec le dernier firmware disponible. Pensez a verifier les mises a jour.' },
      { q: 'Puis-je payer en plusieurs fois ?', a: 'Oui, le paiement en 3x ou 4x sans frais est disponible des 100 euros d achat via notre partenaire bancaire.' },
      { q: 'Comment recycler mon ancien produit ?', a: 'Nous reprenons gratuitement votre ancien appareil lors de la livraison de votre nouveau (eco-participation).' },
    ],
    guardrails: [
      'Ne JAMAIS promettre une compatibilite non verifiee',
      'Toujours rappeler la garantie 2 ans',
      'En cas de produit defectueux, proposer SAV avant remboursement',
      'Ne jamais affirmer un delai de reparation sans verification',
      'Respecter les normes RGPD en cas de demande sur les donnees',
    ],
    playbooks: ['sav_ecommerce', 'post_purchase_followup', 'shipping_tracker'],
  },
  {
    id: 'home',
    name: 'Maison & Deco',
    icon: Home,
    description: 'Decoration, mobilier, art de vivre',
    color: '#8b5cf6',
    brand_tone: 'Inspirant, esthetique, raffine',
    knowledge: [
      { q: 'Delais de livraison des meubles ?', a: '5 a 15 jours ouvres selon le produit. Les delais sont indiques sur chaque fiche produit.' },
      { q: 'Le montage est-il inclus ?', a: 'Non, le montage n est pas inclus mais une notice detaillee est fournie avec chaque meuble.' },
      { q: 'Comment retourner un meuble ?', a: 'Les retours sont possibles sous 14 jours. Les frais de retour sont a votre charge pour les produits volumineux.' },
      { q: 'Quelles sont les dimensions exactes ?', a: 'Les dimensions precises (L x l x H) sont indiquees sur chaque fiche produit. Verifiez vos acces avant commande.' },
      { q: 'Livrez-vous a l etage ?', a: 'Oui, une option de livraison a l etage est disponible en supplement au moment du paiement.' },
      { q: 'Les produits sont-ils faits main ?', a: 'Certaines de nos pieces sont artisanales. La mention "fait main" est indiquee sur la fiche produit concernee.' },
      { q: 'Quelles sont les matieres utilisees ?', a: 'Chaque fiche produit precise les materiaux (bois, metal, tissu). Nous privilegions des matieres durables.' },
      { q: 'Puis-je commander une piece unique sur mesure ?', a: 'Oui, contactez-nous pour un devis personnalise. Les delais sont generalement de 4 a 8 semaines.' },
      { q: 'Comment entretenir mon meuble ?', a: 'Un guide d entretien specifique est fourni avec chaque produit selon la matiere (bois, cuir, textile).' },
      { q: 'Livraison gratuite ?', a: 'Livraison offerte des 150 euros d achat en France metropolitaine, sauf produits volumineux.' },
      { q: 'Les couleurs a l ecran sont-elles fideles ?', a: 'Nous faisons notre possible pour une restitution fidele, de legeres variations sont possibles selon votre ecran.' },
      { q: 'Y a-t-il une garantie ?', a: 'Tous nos meubles sont garantis 2 ans contre tout defaut de fabrication.' },
      { q: 'Que faire si un produit arrive casse ?', a: 'Prenez des photos et contactez-nous dans les 48h. Nous organisons le remplacement ou le remboursement.' },
      { q: 'Avez-vous un service de decoration interieure ?', a: 'Oui, nos conseillers proposent un accompagnement deco gratuit pour les commandes superieures a 500 euros.' },
      { q: 'Les produits sont-ils en stock ?', a: 'La disponibilite est mise a jour en temps reel. Pour les pieces en rupture, une date de reassort est indiquee.' },
    ],
    guardrails: [
      'Toujours preciser les dimensions exactes pour les meubles',
      'En cas de retour de meuble, prevenir les frais de retour',
      'Ne jamais promettre une livraison express sur les gros volumes',
      'Toujours rappeler les delais de fabrication des pieces uniques',
      'Si le client demande un conseil deco, rester factuel sur le produit',
    ],
    playbooks: ['sav_ecommerce', 'shipping_tracker', 'abandoned_cart'],
  },
  {
    id: 'other',
    name: 'Autre',
    icon: Package,
    description: 'Aucun preset, configuration libre',
    color: '#71717a',
    brand_tone: '',
    knowledge: [],
    guardrails: [],
    playbooks: [],
  },
]

export function getPresetById(id) {
  return INDUSTRY_PRESETS.find((p) => p.id === id) || null
}
