/**
 * Integration categories for the dashboard UI.
 * Order matters: this is the display order.
 */
export const INTEGRATION_CATEGORIES = [
  {
    id: 'ecommerce_platform',
    label: 'Plateforme e-commerce',
    description: 'Connectez votre boutique pour synchroniser commandes, clients et produits',
    ids: ['shopify', 'woocommerce', 'webflow'],
  },
  {
    id: 'helpdesk',
    label: 'Helpdesk',
    description: 'Votre IA gère les tickets directement dans votre outil de support',
    ids: ['gorgias', 'zendesk', 'intercom'],
  },
  {
    id: 'tracking',
    label: 'Tracking colis',
    description: 'Répondez instantanément aux questions "où est ma commande ?"',
    ids: ['aftership'],
  },
  {
    id: 'messaging',
    label: 'Messagerie & notifications',
    description: 'Recevez et envoyez via WhatsApp et Slack',
    ids: ['whatsapp', 'slack'],
  },
  {
    id: 'email',
    label: 'Envoi d\'emails',
    description: 'Choisissez votre service d\'envoi pour les réponses de votre agent',
    ids: ['resend', 'smtp_imap'],
  },
  {
    id: 'knowledge',
    label: 'Base de connaissances',
    description: 'Importez vos documents externes pour alimenter votre agent IA',
    ids: ['google_docs', 'notion'],
  },
  {
    id: 'accounting',
    label: 'Comptabilité',
    description: 'Automatisez relances factures et alertes trésorerie',
    ids: ['axonaut', 'pennylane', 'ipaidthat'],
  },
]

/**
 * Conflict groups — only one integration per group can be active at a time.
 * When connecting an integration, any other active integration in the same group
 * must be disconnected first (or the user must choose).
 */
export const CONFLICT_GROUPS = {
  ecommerce_platform: {
    label: 'Plateforme e-commerce',
    message: 'Vous ne pouvez connecter qu\'une seule plateforme e-commerce à la fois.',
    ids: ['shopify', 'woocommerce', 'webflow'],
  },
  helpdesk: {
    label: 'Helpdesk',
    message: 'Vous ne pouvez connecter qu\'un seul helpdesk à la fois.',
    ids: ['gorgias', 'zendesk', 'intercom'],
  },
  email_sending: {
    label: 'Envoi d\'emails',
    message: 'Vous ne pouvez utiliser qu\'un seul service d\'envoi d\'emails à la fois.',
    ids: ['resend', 'smtp_imap'],
  },
}

export function getConflictGroup(integrationId) {
  return Object.entries(CONFLICT_GROUPS).find(([, group]) => group.ids.includes(integrationId))
}

export function getConflictingActive(integrationId, activeIntegrations) {
  const entry = getConflictGroup(integrationId)
  if (!entry) return null
  const [, group] = entry
  return activeIntegrations.find(i => group.ids.includes(i.provider) && i.provider !== integrationId && i.status === 'active')
}

export const INTEGRATIONS = {
  ecommerce: [
    {
      id: 'shopify',
      name: 'Shopify',
      description: 'Synchronisation commandes, clients et produits',
      icon: '/integrations/shopify.png',
      authType: 'oauth',
      oauthPrompt: 'shop',
      oauthPromptLabel: 'Votre domaine Shopify',
      oauthPromptPlaceholder: 'ma-boutique.myshopify.com',
      oauthPromptHint: 'Trouvez-le dans Shopify Admin → Settings → Domains',
      oauthUrl: (params) => `/api/shopify/install?shop=${encodeURIComponent(params.shop)}&token=${encodeURIComponent(params.token || '')}`,
      category: 'ecommerce',
      docsUrl: 'https://help.shopify.com/en/manual/apps',
      color: '#96BF48',
      popular: true,
    },
    {
      id: 'gorgias',
      name: 'Gorgias',
      description: 'Helpdesk e-commerce — tickets SAV, macros, automatisations',
      icon: 'https://ejgdwjjcpjtwaqcxptke.supabase.co/storage/v1/object/public/logo/gorgias.png',
      authType: 'oauth',
      oauthPrompt: 'subdomain',
      oauthPromptLabel: 'Votre sous-domaine Gorgias',
      oauthPromptPlaceholder: 'ma-boutique',
      oauthPromptHint: 'L\'URL de votre compte est ma-boutique.gorgias.com',
      oauthUrl: (params) => `/api/integrations/oauth/gorgias/install?subdomain=${encodeURIComponent(params.subdomain)}&token=${encodeURIComponent(params.token)}`,
      category: 'ecommerce',
      docsUrl: 'https://developers.gorgias.com/docs/authentication',
      color: '#1F1F1F',
      popular: true,
    },
    {
      id: 'zendesk',
      name: 'Zendesk',
      description: 'Helpdesk — tickets, chat, base de connaissances',
      icon: '/integrations/zendesk.svg',
      authType: 'oauth',
      oauthPrompt: 'subdomain',
      oauthPromptLabel: 'Votre sous-domaine Zendesk',
      oauthPromptPlaceholder: 'ma-boutique',
      oauthPromptHint: "L'URL de votre compte est ma-boutique.zendesk.com",
      oauthUrl: (params) => `/api/integrations/oauth/zendesk/install?subdomain=${encodeURIComponent(params.subdomain)}&token=${encodeURIComponent(params.token)}`,
      category: 'ecommerce',
      docsUrl: 'https://developer.zendesk.com/api-reference/',
      color: '#03363D',
    },
    {
      id: 'intercom',
      name: 'Intercom',
      description: 'Helpdesk & messaging — conversations, tickets, base de connaissances',
      icon: 'https://logo.clearbit.com/intercom.com',
      authType: 'oauth',
      oauthUrl: (params) => `/api/integrations/intercom/authorize?client_id=${encodeURIComponent(params.client_id || '')}&token=${encodeURIComponent(params.token || '')}`,
      category: 'ecommerce',
      docsUrl: 'https://developers.intercom.com/docs',
      color: '#1F8DED',
      popular: true,
    },
    {
      id: 'webflow',
      name: 'Webflow',
      description: 'Connectez votre boutique Webflow en 1 clic — commandes, clients, produits',
      icon: 'https://ejgdwjjcpjtwaqcxptke.supabase.co/storage/v1/object/public/logo/WebFlow.png',
      authType: 'oauth',
      oauthUrl: (params) => `/api/integrations/webflow/authorize?client_id=${encodeURIComponent(params.client_id || '')}&token=${encodeURIComponent(params.token || '')}`,
      category: 'ecommerce',
      docsUrl: 'https://developers.webflow.com/docs/getting-started',
      color: '#4353FF',
      popular: true,
    },
    {
      id: 'woocommerce',
      name: 'WooCommerce',
      description: 'Connectez votre boutique WooCommerce en 1 clic — commandes, clients, produits',
      icon: 'https://ejgdwjjcpjtwaqcxptke.supabase.co/storage/v1/object/public/logo/WooCommerce.png',
      authType: 'oauth',
      oauthPrompt: 'store_url',
      oauthPromptLabel: 'URL de votre boutique WooCommerce',
      oauthPromptPlaceholder: 'https://ma-boutique.com',
      oauthPromptHint: 'L\'adresse de votre site WordPress avec WooCommerce installé',
      oauthUrl: (params) => `/api/integrations/woocommerce/authorize?store_url=${encodeURIComponent(params.store_url)}&client_id=${encodeURIComponent(params.client_id || '')}&token=${encodeURIComponent(params.token || '')}`,
      category: 'ecommerce',
      docsUrl: 'https://woocommerce.github.io/woocommerce-rest-api-docs/',
      color: '#96588A',
      popular: true,
    },
    {
      id: 'aftership',
      name: 'AfterShip',
      description: 'Tracking automatique des colis — l\'IA répond instantanément "où est ma commande ?"',
      icon: 'https://logo.clearbit.com/aftership.com',
      authType: 'api_key',
      apiKeyLabel: 'Clé API AfterShip',
      apiKeyPlaceholder: 'asat_xxxxxxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-la dans AfterShip → Settings → API Keys',
      category: 'ecommerce',
      docsUrl: 'https://developers.aftership.com/reference/api-overview',
      color: '#0A2540',
      popular: true,
    },
    {
      id: 'whatsapp',
      name: 'WhatsApp Business',
      description: 'Répondez aux clients directement via WhatsApp',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg',
      authType: 'embedded_signup',
      wizardRoute: '/client/whatsapp-agent',
      category: 'ecommerce',
      docsUrl: 'https://developers.facebook.com/docs/whatsapp',
      color: '#25D366',
      popular: true,
    },
  ],
  general: [
    {
      id: 'slack',
      name: 'Slack',
      description: 'Recevez les alertes et notifications dans votre Slack',
      icon: 'https://a.slack-edge.com/80588/marketing/img/icons/icon_slack_hash_colored.png',
      authType: 'oauth',
      oauthUrl: (params) => `/api/integrations/oauth/slack/install?token=${encodeURIComponent(params.token)}`,
      category: 'general',
      docsUrl: 'https://api.slack.com/messaging/webhooks',
      color: '#4A154B',
      popular: true,
    },
    {
      id: 'resend',
      name: 'Resend',
      description: 'Envoi d\'emails transactionnels — notifications, relances, escalades',
      icon: 'https://ejgdwjjcpjtwaqcxptke.supabase.co/storage/v1/object/public/logo/resend-icon-black.svg',
      authType: 'api_key',
      apiKeyLabel: 'Clé API Resend',
      apiKeyPlaceholder: 're_xxxxxxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-la dans Resend → API Keys → Create API Key',
      category: 'general',
      docsUrl: 'https://resend.com/docs',
      color: '#000000',
      popular: true,
    },
    {
      id: 'axonaut',
      name: 'Axonaut',
      description: 'CRM et facturation pour PME — devis, factures, trésorerie',
      icon: 'https://www.axonaut.com/favicon.ico',
      authType: 'api_key',
      apiKeyLabel: 'Clé API Axonaut',
      apiKeyPlaceholder: 'ak_xxxxxxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-la dans Axonaut → Paramètres → API',
      category: 'general',
      docsUrl: 'https://axonaut.com/api',
      color: '#FF6B35',
    },
    {
      id: 'pennylane',
      name: 'Pennylane',
      description: 'Comptabilité automatisée — rapprochement bancaire, factures, bilan',
      icon: 'https://www.pennylane.com/favicon.ico',
      authType: 'api_key',
      apiKeyLabel: 'Token API Pennylane',
      apiKeyPlaceholder: 'pl_xxxxxxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-le dans Pennylane → Paramètres → Intégrations → API',
      category: 'general',
      docsUrl: 'https://pennylane.com/api',
      color: '#1B1464',
    },
    {
      id: 'ipaidthat',
      name: 'iPaidThat',
      description: 'Collecte et classement automatique de factures et justificatifs',
      icon: 'https://ejgdwjjcpjtwaqcxptke.supabase.co/storage/v1/object/public/logo/iPaidThat.png',
      authType: 'api_key',
      apiKeyLabel: 'Clé API iPaidThat',
      apiKeyPlaceholder: 'ipt_xxxxxxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-la dans iPaidThat → Paramètres → API & Intégrations',
      category: 'general',
      docsUrl: 'https://ipaidthat.io',
      color: '#00B4D8',
    },
    {
      id: 'google_docs',
      name: 'Google Docs',
      description: 'Importez vos documents Google dans la base de connaissances de votre agent IA',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Google_Docs_logo_%282014-2020%29.svg',
      authType: 'oauth',
      oauthUrl: (params) => `/api/integrations/google-docs/authorize?client_id=${encodeURIComponent(params.client_id || '')}&token=${encodeURIComponent(params.token || '')}`,
      category: 'general',
      docsUrl: 'https://developers.google.com/docs/api',
      color: '#4285F4',
      knowledgeBase: true,
      popular: true,
    },
    {
      id: 'notion',
      name: 'Notion',
      description: 'Connectez vos pages Notion pour alimenter la base de connaissances de votre agent',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png',
      authType: 'oauth',
      oauthUrl: (params) => `/api/integrations/notion/authorize?client_id=${encodeURIComponent(params.client_id || '')}&token=${encodeURIComponent(params.token || '')}`,
      category: 'general',
      docsUrl: 'https://developers.notion.com',
      color: '#000000',
      knowledgeBase: true,
      popular: true,
    },
    {
      id: 'smtp_imap',
      name: 'Email personnalisé (SMTP/IMAP)',
      description: 'Connectez votre adresse email professionnelle pour envoyer et recevoir',
      icon: null,
      authType: 'smtp',
      smtpFields: [
        { key: 'email', label: 'Adresse email', type: 'email', placeholder: 'contact@votreboutique.com', required: true },
        { key: 'smtp_host', label: 'Serveur SMTP', type: 'text', placeholder: 'smtp.votrefournisseur.com', required: true },
        { key: 'smtp_port', label: 'Port SMTP', type: 'number', placeholder: '587', required: true },
        { key: 'imap_host', label: 'Serveur IMAP', type: 'text', placeholder: 'imap.votrefournisseur.com', required: true },
        { key: 'imap_port', label: 'Port IMAP', type: 'number', placeholder: '993', required: true },
        { key: 'username', label: 'Identifiant', type: 'text', placeholder: 'contact@votreboutique.com', required: true },
        { key: 'password', label: 'Mot de passe', type: 'password', placeholder: '••••••••', required: true },
        { key: 'use_ssl', label: 'Utiliser SSL/TLS', type: 'toggle', defaultValue: true },
      ],
      category: 'general',
      color: '#6366f1',
      popular: true,
    },
  ],
};

export const ALL_INTEGRATIONS = [
  ...INTEGRATIONS.ecommerce,
  ...INTEGRATIONS.general,
];

export const getIntegrationById = (id) => ALL_INTEGRATIONS.find(i => i.id === id);
