export const INTEGRATIONS = {
  ecommerce: [
    {
      id: 'shopify',
      name: 'Shopify',
      description: 'Synchronisation commandes, clients et produits',
      icon: '/integrations/shopify.png',
      authType: 'oauth',
      oauthPrompt: 'shop',
      oauthPromptLabel: 'Votre domaine Shopify',
      oauthPromptPlaceholder: 'ma-boutique.myshopify.com',
      oauthPromptHint: 'Trouvez-le dans Shopify Admin → Settings → Domains',
      oauthUrl: (params) => `/api/shopify/install?shop=${encodeURIComponent(params.shop)}&token=${encodeURIComponent(params.token || '')}`,
      category: 'ecommerce',
      docsUrl: 'https://help.shopify.com/en/manual/apps',
      color: '#96BF48',
      popular: true,
    },
    {
      id: 'gorgias',
      name: 'Gorgias',
      description: 'Helpdesk e-commerce — tickets SAV, macros, automatisations',
      icon: '/integrations/gorgias.png',
      authType: 'oauth',
      oauthPrompt: 'subdomain',
      oauthPromptLabel: 'Votre sous-domaine Gorgias',
      oauthPromptPlaceholder: 'ma-boutique',
      oauthPromptHint: 'L\'URL de votre compte est ma-boutique.gorgias.com',
      oauthUrl: (params) => `/api/integrations/oauth/gorgias/install?subdomain=${encodeURIComponent(params.subdomain)}&token=${encodeURIComponent(params.token)}`,
      category: 'ecommerce',
      docsUrl: 'https://developers.gorgias.com/docs/authentication',
      color: '#1F1F1F',
      popular: true,
    },
    {
      id: 'zendesk',
      name: 'Zendesk',
      description: 'Helpdesk — tickets, chat, base de connaissances',
      icon: '/integrations/zendesk.svg',
      authType: 'oauth',
      oauthPrompt: 'subdomain',
      oauthPromptLabel: 'Votre sous-domaine Zendesk',
      oauthPromptPlaceholder: 'ma-boutique',
      oauthPromptHint: "L'URL de votre compte est ma-boutique.zendesk.com",
      oauthUrl: (params) => `/api/integrations/oauth/zendesk/install?subdomain=${encodeURIComponent(params.subdomain)}&token=${encodeURIComponent(params.token)}`,
      category: 'ecommerce',
      docsUrl: 'https://developer.zendesk.com/api-reference/',
      color: '#03363D',
    },
    {
      id: 'klaviyo',
      name: 'Klaviyo',
      description: 'Email & SMS marketing — declenchez des sequences automatiquement',
      icon: '/integrations/klaviyo.png',
      authType: 'api_key',
      apiKeyLabel: 'Cle API Klaviyo',
      apiKeyPlaceholder: 'pk_xxxxxxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-la dans Klaviyo → Settings → API Keys',
      category: 'ecommerce',
      docsUrl: 'https://developers.klaviyo.com/en',
      color: '#000000',
      popular: true,
    },
    {
      id: 'webflow',
      name: 'Webflow',
      description: 'Connectez votre boutique Webflow en 1 clic — commandes, clients, produits',
      icon: 'https://ejgdwjjcpjtwaqcxptke.supabase.co/storage/v1/object/public/logo/WebFlow.png',
      authType: 'oauth',
      oauthUrl: (params) => `/api/integrations/webflow/authorize?client_id=${encodeURIComponent(params.client_id || '')}&token=${encodeURIComponent(params.token || '')}`,
      category: 'ecommerce',
      docsUrl: 'https://developers.webflow.com/docs/getting-started',
      color: '#4353FF',
      popular: true,
    },
    {
      id: 'woocommerce',
      name: 'WooCommerce',
      description: 'Connectez votre boutique WooCommerce en 1 clic — commandes, clients, produits',
      icon: 'https://ejgdwjjcpjtwaqcxptke.supabase.co/storage/v1/object/public/logo/WooCommerce.png',
      authType: 'oauth',
      oauthPrompt: 'store_url',
      oauthPromptLabel: 'URL de votre boutique WooCommerce',
      oauthPromptPlaceholder: 'https://ma-boutique.com',
      oauthPromptHint: 'L\'adresse de votre site WordPress avec WooCommerce installe',
      oauthUrl: (params) => `/api/integrations/woocommerce/authorize?store_url=${encodeURIComponent(params.store_url)}&client_id=${encodeURIComponent(params.client_id || '')}&token=${encodeURIComponent(params.token || '')}`,
      category: 'ecommerce',
      docsUrl: 'https://woocommerce.github.io/woocommerce-rest-api-docs/',
      color: '#96588A',
      popular: true,
    },
    {
      id: 'stripe_connect',
      name: 'Stripe',
      description: 'Synchronisez vos paiements Stripe — transactions, remboursements, litiges',
      icon: '/integrations/stripe.png',
      authType: 'api_key',
      apiKeyLabel: 'Cle API Stripe (restricted key)',
      apiKeyPlaceholder: 'rk_live_xxx...',
      apiKeyHint: 'Stripe Dashboard → Developpeurs → Cles API → Cle restreinte',
      category: 'ecommerce',
      docsUrl: 'https://stripe.com/docs/api',
      color: '#635BFF',
    },
    {
      id: 'whatsapp',
      name: 'WhatsApp Business',
      description: 'Repondez aux clients directement via WhatsApp',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg',
      authType: 'embedded_signup',
      wizardRoute: '/client/whatsapp-agent',
      category: 'ecommerce',
      docsUrl: 'https://developers.facebook.com/docs/whatsapp',
      color: '#25D366',
      popular: true,
    },
  ],
  general: [
    {
      id: 'slack',
      name: 'Slack',
      description: 'Recevez les alertes et notifications dans votre Slack',
      icon: 'https://a.slack-edge.com/80588/marketing/img/icons/icon_slack_hash_colored.png',
      authType: 'oauth',
      oauthUrl: (params) => `/api/integrations/oauth/slack/install?token=${encodeURIComponent(params.token)}`,
      category: 'general',
      docsUrl: 'https://api.slack.com/messaging/webhooks',
      color: '#4A154B',
      popular: true,
    },
    {
      id: 'google_sheets',
      name: 'Google Sheets',
      description: 'Export automatique de vos donnees vers Google Sheets',
      icon: 'https://ssl.gstatic.com/docs/spreadsheets/favicon3.ico',
      authType: 'oauth',
      oauthUrl: (params) => `/api/integrations/oauth/google/install?token=${encodeURIComponent(params.token)}`,
      category: 'general',
      docsUrl: 'https://developers.google.com/sheets/api',
      color: '#0F9D58',
    },
    {
      id: 'resend',
      name: 'Resend',
      description: 'Envoi d\'emails transactionnels — notifications, relances, escalades',
      icon: 'https://resend.com/static/favicons/favicon-32x32.png',
      authType: 'api_key',
      apiKeyLabel: 'Cle API Resend',
      apiKeyPlaceholder: 're_xxxxxxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-la dans Resend → API Keys → Create API Key',
      category: 'general',
      docsUrl: 'https://resend.com/docs',
      color: '#000000',
      popular: true,
    },
    {
      id: 'axonaut',
      name: 'Axonaut',
      description: 'CRM et facturation pour PME — devis, factures, tresorerie',
      icon: 'https://www.axonaut.com/favicon.ico',
      authType: 'api_key',
      apiKeyLabel: 'Cle API Axonaut',
      apiKeyPlaceholder: 'ak_xxxxxxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-la dans Axonaut → Parametres → API',
      category: 'general',
      docsUrl: 'https://axonaut.com/api',
      color: '#FF6B35',
    },
    {
      id: 'pennylane',
      name: 'Pennylane',
      description: 'Comptabilite automatisee — rapprochement bancaire, factures, bilan',
      icon: 'https://www.pennylane.com/favicon.ico',
      authType: 'api_key',
      apiKeyLabel: 'Token API Pennylane',
      apiKeyPlaceholder: 'pl_xxxxxxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-le dans Pennylane → Parametres → Integrations → API',
      category: 'general',
      docsUrl: 'https://pennylane.com/api',
      color: '#1B1464',
    },
    {
      id: 'ipaidthat',
      name: 'iPaidThat',
      description: 'Collecte et classement automatique de factures et justificatifs',
      icon: 'https://www.ipaidthat.io/favicon.ico',
      authType: 'api_key',
      apiKeyLabel: 'Cle API iPaidThat',
      apiKeyPlaceholder: 'ipt_xxxxxxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-la dans iPaidThat → Parametres → API & Integrations',
      category: 'general',
      docsUrl: 'https://ipaidthat.io',
      color: '#00B4D8',
    },
    {
      id: 'smtp_imap',
      name: 'Email personnalise (SMTP/IMAP)',
      description: 'Connectez votre adresse email professionnelle pour envoyer et recevoir',
      icon: null,
      authType: 'smtp',
      smtpFields: [
        { key: 'email', label: 'Adresse email', type: 'email', placeholder: 'contact@votreboutique.com', required: true },
        { key: 'smtp_host', label: 'Serveur SMTP', type: 'text', placeholder: 'smtp.votrefournisseur.com', required: true },
        { key: 'smtp_port', label: 'Port SMTP', type: 'number', placeholder: '587', required: true },
        { key: 'imap_host', label: 'Serveur IMAP', type: 'text', placeholder: 'imap.votrefournisseur.com', required: true },
        { key: 'imap_port', label: 'Port IMAP', type: 'number', placeholder: '993', required: true },
        { key: 'username', label: 'Identifiant', type: 'text', placeholder: 'contact@votreboutique.com', required: true },
        { key: 'password', label: 'Mot de passe', type: 'password', placeholder: '••••••••', required: true },
        { key: 'use_ssl', label: 'Utiliser SSL/TLS', type: 'toggle', defaultValue: true },
      ],
      category: 'general',
      color: '#6366f1',
      popular: true,
    },
  ],
};

export const ALL_INTEGRATIONS = [
  ...INTEGRATIONS.ecommerce,
  ...INTEGRATIONS.general,
];

export const getIntegrationById = (id) => ALL_INTEGRATIONS.find(i => i.id === id);
