export const INTEGRATIONS = {
  ecommerce: [
    {
      id: 'shopify',
      name: 'Shopify',
      description: 'Synchronisation commandes, clients et produits',
      icon: '/integrations/shopify.png',
      authType: 'oauth',
      oauthPrompt: 'shop',
      oauthPromptLabel: 'Votre domaine Shopify',
      oauthPromptPlaceholder: 'ma-boutique.myshopify.com',
      oauthPromptHint: 'Trouvez-le dans Shopify Admin → Settings → Domains',
      oauthUrl: (params) => `/api/shopify/install?shop=${encodeURIComponent(params.shop)}&token=${encodeURIComponent(params.token || '')}`,
      category: 'ecommerce',
      docsUrl: 'https://help.shopify.com/en/manual/apps',
      color: '#96BF48',
      popular: true,
    },
    {
      id: 'gorgias',
      name: 'Gorgias',
      description: 'Helpdesk e-commerce — tickets SAV, macros, automatisations',
      icon: '/integrations/gorgias.png',
      authType: 'oauth',
      oauthPrompt: 'subdomain',
      oauthPromptLabel: 'Votre sous-domaine Gorgias',
      oauthPromptPlaceholder: 'ma-boutique',
      oauthPromptHint: 'L\'URL de votre compte est ma-boutique.gorgias.com',
      oauthUrl: (params) => `/api/integrations/oauth/gorgias/install?subdomain=${encodeURIComponent(params.subdomain)}&token=${encodeURIComponent(params.token)}`,
      category: 'ecommerce',
      docsUrl: 'https://developers.gorgias.com/docs/authentication',
      color: '#1F1F1F',
      popular: true,
    },
    {
      id: 'zendesk',
      name: 'Zendesk',
      description: 'Helpdesk — tickets, chat, base de connaissances',
      icon: '/integrations/zendesk.svg',
      authType: 'oauth',
      oauthPrompt: 'subdomain',
      oauthPromptLabel: 'Votre sous-domaine Zendesk',
      oauthPromptPlaceholder: 'ma-boutique',
      oauthPromptHint: "L'URL de votre compte est ma-boutique.zendesk.com",
      oauthUrl: (params) => `/api/integrations/oauth/zendesk/install?subdomain=${encodeURIComponent(params.subdomain)}&token=${encodeURIComponent(params.token)}`,
      category: 'ecommerce',
      docsUrl: 'https://developer.zendesk.com/api-reference/',
      color: '#03363D',
    },
    {
      id: 'klaviyo',
      name: 'Klaviyo',
      description: 'Email & SMS marketing — declenchez des sequences automatiquement',
      icon: '/integrations/klaviyo.png',
      authType: 'api_key',
      apiKeyLabel: 'Cle API Klaviyo',
      apiKeyPlaceholder: 'pk_xxxxxxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-la dans Klaviyo → Settings → API Keys',
      category: 'ecommerce',
      docsUrl: 'https://developers.klaviyo.com/en',
      color: '#000000',
      popular: true,
    },
    {
      id: 'whatsapp',
      name: 'WhatsApp Business',
      description: 'Repondez aux clients directement via WhatsApp',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg',
      authType: 'api_key',
      apiKeyLabel: 'Token WhatsApp Business API',
      apiKeyPlaceholder: 'EAAxxxxxxx...',
      apiKeyHint: 'Configurez via Meta Business Suite → WhatsApp → API Setup',
      category: 'ecommerce',
      docsUrl: 'https://developers.facebook.com/docs/whatsapp',
      color: '#25D366',
      popular: true,
    },
    {
      id: 'intercom',
      name: 'Intercom',
      description: 'Chat en direct augmente par l\'IA — conversations, inbox',
      icon: 'https://www.intercom.com/favicon.ico',
      authType: 'api_key',
      apiKeyLabel: 'Token d\'acces Intercom',
      apiKeyPlaceholder: 'dG9rOxxxxxxx...',
      apiKeyHint: 'Trouvez-le dans Intercom → Settings → Developers → Access Token',
      category: 'ecommerce',
      docsUrl: 'https://developers.intercom.com/docs',
      color: '#1F8CEB',
    },
    {
      id: 'crisp',
      name: 'Crisp',
      description: 'Chat live, chatbot et inbox multicanal',
      icon: 'https://crisp.chat/favicon-512x512.png',
      authType: 'api_key',
      apiKeyLabel: 'Identifiant de site Crisp',
      apiKeyPlaceholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-le dans Crisp → Settings → Website Settings → Setup instructions',
      category: 'ecommerce',
      docsUrl: 'https://docs.crisp.chat/api/v1/',
      color: '#4B5CFF',
    },
    {
      id: 'freshdesk',
      name: 'Freshdesk',
      description: 'Helpdesk — tickets, automatisations, base de connaissances',
      icon: '/integrations/freshdesk.svg',
      authType: 'api_key',
      apiKeyLabel: 'Cle API Freshdesk',
      apiKeyPlaceholder: 'xxxxxxxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-la dans Freshdesk → Profile → API Key',
      category: 'ecommerce',
      docsUrl: 'https://developers.freshdesk.com/api/',
      color: '#25C16F',
    },
    {
      id: 'trustpilot',
      name: 'Trustpilot',
      description: 'Monitoring des avis clients en temps reel',
      icon: 'https://www.trustpilot.com/favicon.ico',
      authType: 'coming_soon',
      category: 'ecommerce',
      docsUrl: 'https://documentation-apidocumentation.trustpilot.com/',
      color: '#00B67A',
    },
  ],
  immobilier: [
    {
      id: 'apimo',
      name: 'Apimo',
      description: 'CRM immobilier — biens, mandats, contacts, matching',
      icon: '/integrations/apimo.svg',
      authType: 'coming_soon',
      category: 'immobilier',
      docsUrl: 'https://api.apimo.pro/doc',
      color: '#E94E1B',
    },
    {
      id: 'hektor',
      name: 'Hektor',
      description: 'CRM immobilier — gestion des biens et contacts',
      icon: '/integrations/hektor.svg',
      authType: 'coming_soon',
      category: 'immobilier',
      color: '#2C3E50',
    },
    {
      id: 'netty',
      name: 'Netty',
      description: 'Logiciel immobilier — diffusion, CRM, site web',
      icon: '/integrations/netty.svg',
      authType: 'coming_soon',
      category: 'immobilier',
      color: '#FF6B00',
    },
  ],
  general: [
    {
      id: 'slack',
      name: 'Slack',
      description: 'Recevez les alertes et notifications dans votre Slack',
      icon: 'https://a.slack-edge.com/80588/marketing/img/icons/icon_slack_hash_colored.png',
      authType: 'oauth',
      oauthUrl: (params) => `/api/integrations/oauth/slack/install?token=${encodeURIComponent(params.token)}`,
      category: 'general',
      docsUrl: 'https://api.slack.com/messaging/webhooks',
      color: '#4A154B',
      popular: true,
    },
    {
      id: 'google_sheets',
      name: 'Google Sheets',
      description: 'Export automatique de vos données vers Google Sheets',
      icon: 'https://ssl.gstatic.com/docs/spreadsheets/favicon3.ico',
      authType: 'oauth',
      oauthUrl: (params) => `/api/integrations/oauth/google/install?token=${encodeURIComponent(params.token)}`,
      category: 'general',
      docsUrl: 'https://developers.google.com/sheets/api',
      color: '#0F9D58',
    },
    {
      id: 'calendly',
      name: 'Calendly',
      description: 'Prise de rendez-vous automatique pour vos prospects',
      icon: 'https://www.calendly.com/favicon.ico',
      authType: 'api_key',
      apiKeyLabel: 'Token personnel Calendly',
      apiKeyPlaceholder: 'eyJxxxxxxx...',
      apiKeyHint: 'Trouvez-le dans Calendly → Integrations → API & Webhooks',
      category: 'general',
      docsUrl: 'https://developer.calendly.com/',
      color: '#006BFF',
      popular: true,
    },
    {
      id: 'cal_com',
      name: 'Cal.com',
      description: 'Alternative open-source a Calendly — prise de RDV',
      icon: 'https://cal.com/favicon.ico',
      authType: 'api_key',
      apiKeyLabel: 'Cle API Cal.com',
      apiKeyPlaceholder: 'cal_live_xxxxxxx',
      apiKeyHint: 'Trouvez-la dans Cal.com → Settings → Developer → API Keys',
      category: 'general',
      docsUrl: 'https://cal.com/docs/api',
      color: '#292929',
    },
    {
      id: 'gmail',
      name: 'Gmail',
      description: 'Envoi et reception d\'emails via votre compte Gmail',
      icon: 'https://ssl.gstatic.com/ui/v1/icons/mail/rfr/gmail.ico',
      authType: 'oauth',
      oauthUrl: (params) => `/api/integrations/oauth/gmail/install?token=${encodeURIComponent(params.token)}`,
      category: 'general',
      docsUrl: 'https://developers.google.com/gmail/api',
      color: '#EA4335',
    },
    {
      id: 'axonaut',
      name: 'Axonaut',
      description: 'CRM et facturation pour PME — devis, factures, tresorerie',
      icon: 'https://www.axonaut.com/favicon.ico',
      authType: 'api_key',
      apiKeyLabel: 'Cle API Axonaut',
      apiKeyPlaceholder: 'ak_xxxxxxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-la dans Axonaut → Parametres → API',
      category: 'general',
      docsUrl: 'https://axonaut.com/api',
      color: '#FF6B35',
    },
    {
      id: 'pennylane',
      name: 'Pennylane',
      description: 'Comptabilite automatisee — rapprochement bancaire, factures, bilan',
      icon: 'https://www.pennylane.com/favicon.ico',
      authType: 'api_key',
      apiKeyLabel: 'Token API Pennylane',
      apiKeyPlaceholder: 'pl_xxxxxxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-le dans Pennylane → Parametres → Integrations → API',
      category: 'general',
      docsUrl: 'https://pennylane.com/api',
      color: '#1B1464',
    },
    {
      id: 'ipaidthat',
      name: 'iPaidThat',
      description: 'Collecte et classement automatique de factures et justificatifs',
      icon: 'https://www.ipaidthat.io/favicon.ico',
      authType: 'api_key',
      apiKeyLabel: 'Cle API iPaidThat',
      apiKeyPlaceholder: 'ipt_xxxxxxxxxxxxxxxx',
      apiKeyHint: 'Trouvez-la dans iPaidThat → Parametres → API & Integrations',
      category: 'general',
      docsUrl: 'https://ipaidthat.io',
      color: '#00B4D8',
    },
    {
      id: 'smtp_imap',
      name: 'Email personnalise (SMTP/IMAP)',
      description: 'Connectez n\'importe quelle adresse email professionnelle (contact@votreboutique.com)',
      icon: null,
      authType: 'smtp',
      smtpFields: [
        { key: 'email', label: 'Adresse email', type: 'email', placeholder: 'contact@votreboutique.com', required: true },
        { key: 'smtp_host', label: 'Serveur SMTP', type: 'text', placeholder: 'smtp.votrefournisseur.com', required: true },
        { key: 'smtp_port', label: 'Port SMTP', type: 'number', placeholder: '587', required: true },
        { key: 'imap_host', label: 'Serveur IMAP', type: 'text', placeholder: 'imap.votrefournisseur.com', required: true },
        { key: 'imap_port', label: 'Port IMAP', type: 'number', placeholder: '993', required: true },
        { key: 'username', label: 'Identifiant', type: 'text', placeholder: 'contact@votreboutique.com', required: true },
        { key: 'password', label: 'Mot de passe', type: 'password', placeholder: '••••••••', required: true },
        { key: 'use_ssl', label: 'Utiliser SSL/TLS', type: 'toggle', defaultValue: true },
      ],
      category: 'general',
      color: '#6366f1',
      popular: true,
    },
  ],
};

export const ALL_INTEGRATIONS = [
  ...INTEGRATIONS.ecommerce,
  ...INTEGRATIONS.immobilier,
  ...INTEGRATIONS.general,
];

export const getIntegrationById = (id) => ALL_INTEGRATIONS.find(i => i.id === id);
