"""
Actero — Gorgias historical ticket migration (E2B sandbox).

Pulls all (or filtered) tickets from a Gorgias account via the v1 API and
imports them into Actero's `ai_conversations` table so the engine can learn
from real merchant history.

Env (passed by api/lib/e2b-runner.js):
  GORGIAS_SUBDOMAIN, GORGIAS_API_KEY, GORGIAS_EMAIL,
  CLIENT_ID, JOB_ID, JOB_PAYLOAD, SUPABASE_URL, SUPABASE_SERVICE_KEY

Gorgias API ref: https://developers.gorgias.com/reference/list-tickets
Auth: Basic <email:api_key> base64.
"""

from __future__ import annotations
import os
import sys
import base64
import time
from datetime import datetime, timezone
from typing import Iterable

sys.path.insert(0, "/")
from lib_actero import job_progress, supabase_request, load_payload, safe_main, fail  # noqa: E402

import requests  # noqa: E402

SUBDOMAIN = os.environ.get("GORGIAS_SUBDOMAIN")
EMAIL = os.environ.get("GORGIAS_EMAIL")
API_KEY = os.environ.get("GORGIAS_API_KEY")
CLIENT_ID = os.environ.get("CLIENT_ID")

BASE = f"https://{SUBDOMAIN}.gorgias.com/api"


def auth_header() -> dict:
    creds = f"{EMAIL}:{API_KEY}".encode("utf-8")
    encoded = base64.b64encode(creds).decode("ascii")
    return {"Authorization": f"Basic {encoded}", "Accept": "application/json"}


def gorgias_get(path: str, params: dict | None = None) -> dict:
    r = requests.get(f"{BASE}{path}", headers=auth_header(), params=params, timeout=30)
    if r.status_code == 429:
        time.sleep(int(r.headers.get("Retry-After", "5")))
        return gorgias_get(path, params)
    r.raise_for_status()
    return r.json()


def iter_tickets(since: str | None, limit: int | None) -> Iterable[dict]:
    cursor = None
    fetched = 0
    while True:
        params = {"limit": 100, "order_by": "created_datetime:desc"}
        if cursor:
            params["cursor"] = cursor
        if since:
            params["created_datetime[gte]"] = since
        data = gorgias_get("/tickets", params)
        for t in data.get("data", []):
            yield t
            fetched += 1
            if limit and fetched >= limit:
                return
        meta = data.get("meta", {})
        cursor = meta.get("next_cursor")
        if not cursor:
            return


def to_actero_row(ticket: dict, messages: list[dict]) -> dict:
    """Transform a Gorgias ticket+messages into an ai_conversations row."""
    customer = ticket.get("customer") or {}
    sorted_msgs = sorted(messages, key=lambda m: m.get("created_datetime") or "")

    customer_msg = next(
        (m.get("body_text") or m.get("body_html") or "" for m in sorted_msgs
         if m.get("from_agent") is False),
        "",
    )
    agent_msg = next(
        (m.get("body_text") or m.get("body_html") or "" for m in sorted_msgs
         if m.get("from_agent") is True),
        "",
    )

    return {
        "client_id": CLIENT_ID,
        "channel": "imported_gorgias",
        "customer_email": (customer.get("email") or "")[:255],
        "customer_name": (customer.get("name") or "")[:255],
        "subject": (ticket.get("subject") or "")[:500],
        "user_message": customer_msg[:20_000],
        "ai_response": "",  # historical — not generated by us
        "human_response": agent_msg[:20_000],
        "intent": ticket.get("category") or None,
        "created_at": ticket.get("created_datetime"),
        "added_to_kb": True,
        "metadata": {
            "imported_from": "gorgias",
            "gorgias_ticket_id": ticket.get("id"),
            "tags": [t.get("name") for t in (ticket.get("tags") or [])],
        },
    }


def main() -> None:
    if not (SUBDOMAIN and EMAIL and API_KEY and CLIENT_ID):
        fail("Missing GORGIAS_SUBDOMAIN / GORGIAS_EMAIL / GORGIAS_API_KEY / CLIENT_ID")

    payload = load_payload()
    since = payload.get("since")
    limit = payload.get("limit")

    job_progress(2, "Connecting to Gorgias…")
    try:
        gorgias_get("/users")  # cheapest auth check
    except Exception as e:
        fail(f"Gorgias auth failed: {e}")

    job_progress(5, "Fetching tickets…")

    imported = 0
    skipped = 0
    batch = []
    last_progress = 0

    for ticket in iter_tickets(since=since, limit=limit):
        ticket_id = ticket.get("id")
        # Pull messages for this ticket. (Gorgias /tickets/:id returns enough data.)
        try:
            full = gorgias_get(f"/tickets/{ticket_id}")
            messages = full.get("messages", [])
        except Exception as e:
            sys.stderr.write(f"[ticket {ticket_id}] skipped: {e}\n")
            skipped += 1
            continue

        row = to_actero_row(full, messages)
        batch.append(row)
        if len(batch) >= 50:
            resp = supabase_request(
                "POST", "/rest/v1/ai_conversations", json=batch,
                prefer="resolution=merge-duplicates",
            )
            if resp.ok:
                imported += len(batch)
            else:
                skipped += len(batch)
            batch = []

        # Throttle progress writes to once per ~5%.
        if limit:
            new_progress = min(95, int((imported / max(limit, 1)) * 90) + 5)
        else:
            new_progress = min(95, 5 + (imported // 100))
        if new_progress > last_progress + 4:
            job_progress(new_progress, f"Imported {imported} tickets…")
            last_progress = new_progress

    if batch:
        resp = supabase_request(
            "POST", "/rest/v1/ai_conversations", json=batch,
            prefer="resolution=merge-duplicates",
        )
        if resp.ok:
            imported += len(batch)

    summary = {
        "provider": "gorgias",
        "imported": imported,
        "skipped": skipped,
        "since": since,
    }

    job_progress(
        100,
        f"Migration done — {imported} tickets imported (skipped {skipped})",
        final_status="completed",
        result=summary,
    )


if __name__ == "__main__":
    safe_main(main)
